SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH,'%Y-%m-%d') as date_of_birth
FROM MEMBER_PROFILE
WHERE GENDER='W' 
AND month(DATE_OF_BIRTH)=03
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;